// npm run fixtures:capture -- --dir DIR --source TEXT [--out FILE]
//
// Runs every case from fixture-inputs.ts against one built artifact under
// Node and records what each call returned. The committed fixture was
// captured from the scolta-core main branch before the slim artifact existed,
// so the browser tests hold both new artifacts to the outputs of the code
// they replaced. Recapture only for a deliberate behavior change, and say so
// in the CHANGELOG.

import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { identifyDir } from "./artifacts.js";
import { FIXED_NOW_MS, argument, parityCases } from "./fixture-inputs.js";

export interface CaseResult {
  fn: string;
  input: unknown;
  /** The return value, parsed when it is JSON. */
  output?: unknown;
  error?: string;
}

type Exports = Record<string, unknown> & { initSync: (arg: { module: Uint8Array }) => unknown };

/** Load an artifact's glue and module in Node, with the clock pinned. */
export async function loadInNode(dir: string): Promise<Exports> {
  const spec = identifyDir(dir);
  Date.now = () => FIXED_NOW_MS;
  const glue = (await import(pathToFileURL(resolve(dir, `${spec.stem}.js`)).href)) as Exports;
  glue.initSync({ module: readFileSync(join(dir, `${spec.stem}_bg.wasm`)) });
  return glue;
}

export function runCase(glue: Exports, fn: string, input: unknown): CaseResult {
  const f = glue[fn];
  if (typeof f !== "function") {
    return { fn, input, error: `no export ${fn}` };
  }
  try {
    return { fn, input, output: parseOutput(String((f as (arg: string) => unknown)(argument(input)))) };
  } catch (e) {
    return { fn, input, error: e instanceof Error ? e.message : String(e) };
  }
}

async function main(argv: readonly string[]): Promise<number> {
  let dir: string | undefined;
  let source: string | undefined;
  let out = "tests/fixtures/search-parity.json";
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = argv[i + 1];
    if (next === undefined) throw new Error(`${arg} needs a value`);
    if (arg === "--dir") dir = next;
    else if (arg === "--source") source = next;
    else if (arg === "--out") out = next;
    else throw new Error(`unknown argument: ${arg}`);
    i++;
  }
  if (dir === undefined || source === undefined) {
    throw new Error("usage: capture-fixtures --dir DIR --source TEXT [--out FILE]");
  }
  const glue = await loadInNode(dir);
  const cases = parityCases().map(({ fn, input }) => runCase(glue, fn, input));
  const fixture = {
    $comment:
      "Generated by `npm run fixtures:capture`. Inputs come from tools/src/fixture-inputs.ts; outputs were captured from the build named in captured_from. Do not edit by hand.",
    captured_from: source,
    fixed_now: new Date(FIXED_NOW_MS).toISOString(),
    node: process.version,
    cases,
  };
  // One case per line: compact, and a changed output diffs as one line.
  const { cases: _, ...header } = fixture;
  const head = JSON.stringify(header, null, 1).replace(/\n}$/, "");
  writeFileSync(out, `${head},\n "cases": [\n${cases.map((c) => JSON.stringify(c)).join(",\n")}\n ]\n}\n`);
  process.stdout.write(`wrote ${cases.length} cases to ${out}\n`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exitCode = await main(process.argv.slice(2));
}

/** Exports return JSON text, except the few that return a bare string. */
function parseOutput(text: string): unknown {
  try {
    return JSON.parse(text) as unknown;
  } catch {
    return text;
  }
}
